Added SetTargetEntity for point_proximity_sensor
StrataSource/FGD pull request #213
Opened 2023-11-17 10:44 UTC by MyGamepedia

point_proximity_sensor has SetTargetEntity input, which is not in .fgd by default.

2023-11-17 10:50 UTC, MyGamepedia commented
My first pull request, hope nothing is wrong.

2023-11-17 16:06 UTC, craftablescience requested changes
Please remove the extraneous formatting above line 15

2023-11-17 16:22 UTC, MyGamepedia commented
> Please remove the extraneous formatting above line 15

Removed.

2023-11-17 16:37 UTC, MyGamepedia commented
> Sorry, I meant _all_ the formatting changes above line 15. That's a good start though!

Ah! Misunderstand, sorry, HAHA! File changed again.

2024-01-19 06:00 UTC, craftablescience approved these changes

2024-01-19 06:22 UTC, merged